name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --framework net6.0 --no-restore
    - name: Test
      run: dotnet test  --configuration Release --framework net6.0 --no-restore --verbosity normal
